### ISSUE TITLE
Several blank lines in multi-line scalar values collapsed to one

### ISSUE THREAD

**Issue by Witiko** [api7/lua-tinyyaml#10]
See https://github.com/peposso/lua-tinyyaml/issues/13:

> The following two YAML documents will produce the same output when passed to `tinyyaml.parse()`.
> 
> ``` lua
> first_input = [[
> abstract: |
>   This is *the abstract*.
>   It consists of two paragraphs.
> ]]
> 
> second_input = [[
> abstract: |
>   This is *the abstract*.
> 
>   It consists of two paragraphs.
> ]]
> 
> tinyyaml = require("tinyyaml")
> for k, v in pairs(tinyyaml.parse(first_input)) do
>   print(k, v)
> end
> for k, v in pairs(tinyyaml.parse(second_input)) do
>   print(k, v)
> end
> ```
> 
> Executing the above code in Lua 5.2.4 and in Lua 5.3 gives me the following results:
> 
> ```
> abstract        This is *the abstract*.
> It consists of two paragraphs.
> 
> abstract        This is *the abstract*.
> It consists of two paragraphs.
> 
> ```
> 
> Here is the expected output:
> 
> ```
> abstract        This is *the abstract*.
> It consists of two paragraphs.
> 
> abstract        This is *the abstract*.
> 
> It consists of two paragraphs.
> 
> ```

The following seems to be the cause:
https://github.com/api7/lua-tinyyaml/blob/fe0e8e50cb18ecb0f38398203af18cbf86cd88a8/tinyyaml.lua#L358

This behavior is contrary to the YAML spec (emphasis mine):

> The literal style is denoted by the “|” indicator. It is the simplest, most restricted, and most readable scalar style. [...] Inside literal scalars, all (indented) characters are considered to be content, including white space characters. Note that all line break characters are normalized. In addition, *empty lines are not folded*, though final line breaks and trailing empty lines are chomped.
> 
> — [YAML Ain’t Markup Language (YAML™) Version 1.2, 3rd Edition, Patched at 2009-10-01, Section 8.1.2. Literal Style](https://yaml.org/spec/1.2/#id2795688)

**Comment by spacewander** [comment]
The empty lines are removed from the beginning...
https://github.com/api7/lua-tinyyaml/blob/264ceadeed6521a78884c2e034c04588f255e153/tinyyaml.lua#L719

**Comment by Witiko** [comment]
@spacewander You are right. Is this intentional, or should I take a stab at fixing it? In my application of YAML, blank lines are meaningful.

**Comment by spacewander** [comment]
I think the author missed this corner case.

**Comment by kalekje** [comment]
Upvoting this! Noticed the same issue.

**Comment by Witiko** [comment]
@spacewander @kalekje I propose a fix in #11.
