### ISSUE TITLE
Upload to CTAN

### ISSUE THREAD

**Issue by zepinglee** [api7/lua-tinyyaml#23]
Hi, I'm a developer from the TeX community and I'm writing to let you know that it's planned to distribute the `lua-tinyyaml` package to [CTAN](https://www.ctan.org/) under the MIT license.

Currently this package is included as a part of [`markdown`](https://www.ctan.org/pkg/markdown) package in [CTAN](https://www.ctan.org/) and it's also required by other TeX packages (like [`yamlvars`](https://github.com/kalekje/yamlvars) as well as [citeproc-lua](https://github.com/zepinglee/citeproc-lua) with a [working-in-progress feature](https://github.com/zepinglee/citeproc-lua/pull/29)). After a discussion (<https://github.com/Witiko/markdown/issues/218>), we agree that it will simplify the package dependencies if `lua-tinyyaml` is distributed in CTAN as a standalone package. Are you interested in publishing the `lua-tinyyaml` to CTAN or I'll perform the uploading instead?

**Comment by tzssangglass** [comment]
I don't have the energy to maintain this repository for distribution under CTAN. I think you can fork and distribute this repository under the MIT LICENSE rules.

What's your opinion? @spacewander @membphis

**Comment by spacewander** [comment]
Agree with @tzssangglass. As Neither @tzssangglass nor I use CTAN, it may be inappropriate to do so.

**Comment by zepinglee** [comment]
I understand.

**Comment by muzimuzhi** [comment]
@zepinglee I saw `lua-tinyyaml` was uploaded to CTAN (https://www.ctan.org/pkg/lua-tinyyaml), with Bug tracker and Repository directed to `api/lua-tinyyaml`
```
Bug tracker | https://github.com/api7/lua-tinyyaml/issues
Repository  | https://github.com/api7/lua-tinyyaml
```
And in your fork https://github.com/zepinglee/lua-tinyyaml there's no issue tab.  Are these all indented?

**Comment by zepinglee** [comment]
> @zepinglee I saw `lua-tinyyaml` was uploaded to CTAN (https://www.ctan.org/pkg/lua-tinyyaml), with Bug tracker and Repository directed to `api/lua-tinyyaml`
> 
> ```
> Bug tracker | https://github.com/api7/lua-tinyyaml/issues
> Repository  | https://github.com/api7/lua-tinyyaml
> ```
> 
> And in your fork https://github.com/zepinglee/lua-tinyyaml there's no issue tab. Are these all indented?

Yes. I don't plan to make a division branch.

**Comment by muzimuzhi** [comment]
But ... is `api7/lua-tinyyaml` ready to receive and handle issues reported by LuaTeX users?  I mean, perhaps there will be issues involving `lua-tinyyaml` and LuaTeX ecosystem, not `lua-tinyyaml` alone.

**Comment by zepinglee** [comment]
> But ... is `api7/lua-tinyyaml` ready to receive and handle issues reported by LuaTeX users? I mean, perhaps there will be issues involving `lua-tinyyaml` and LuaTeX ecosystem, not `lua-tinyyaml` alone.

`lua-tinyyaml` is a pure Lua library and has nothing related to TeX.

**Comment by muzimuzhi** [comment]
LuaTeX provides a special Lua env with several preloaded familiar-to-general-lua-user modules like `peg` (but without `re`) and `luafilesystem`, LuaTeX callbacks, and TeX related libraries.  If the issue comes from interaction between `lua-tinyyaml` and the LuaTeX-specific Lua parts then ... . Also directing to `api7/lua-tinyyaml` requires every time a LuaTeX user wants to report or request something a pure-lua example should be prepared.

One solution would be, one or more of you and maintainers of CTAN packages that depend on `lua-tinyyaml` watch and help with `api7/lua-tinyyaml`.
