### ISSUE TITLE
Unescaping quotes fails

### ISSUE THREAD

**Issue by zepinglee** [api7/lua-tinyyaml#25]
`lua-tinyyaml` v0.4.2 fails to unescape single quotes. According to the [spec](https://yaml.org/spec/1.2.2/#single-quoted-style):

> The single-quoted style is specified by surrounding “'” indicators. Therefore, within a single-quoted scalar, such characters need to be repeated. This is the only form of escaping performed in single-quoted scalars.

```lua
  busted.it("string: single quote", function()
    assert.same(
      "here's to \"quotes\"",
      yaml.parse([[
        'here''s to "quotes"'
      ]])
    )
  end)

  busted.it("string: single quote in value", function()
    assert.same(
      {
        title = "User's guide"
      },
      yaml.parse([[
        title: 'User''s guide'
      ]])
    )
  end)
```

`lua-tinyyaml` v0.4.2 (with Lua 5.4) gives:

```
Failure → spec/string_spec.lua @ 183
string string: unescape single quote in mapping value
spec/string_spec.lua:184: Expected objects to be the same.
Passed in:
(table) {
 *[title] = 'User' }
Expected:
(table: 0x7fd7bafe5020) {
 *[title] = 'User''s guide' }

Error → spec/string_spec.lua @ 174
string string: unescape single quote
./tinyyaml.lua:712: failed to classify line:         'here''s to "quotes"'
```

**Comment by tzssangglass** [comment]
hi @zepinglee , would you like to fix it?

**Comment by zepinglee** [comment]
I'll try. BTW have you considered a [`lpeg`](https://luarocks.org/modules/gvvaughan/lpeg)-based approach for the parser?

**Comment by tzssangglass** [comment]
> I'll try. BTW have you considered a [`lpeg`](https://luarocks.org/modules/gvvaughan/lpeg)-based approach for the parser?

No, this lib is mainly intended to serve Apache APISIX, and I wouldn't change it without a necessary reason, it's currently sufficient.
